fix(docs.theme): Fix build error
```
src/components/toc.tsx(78,21): error TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type '{ 2: string; 3: string; 4: string; 5: string; 6: string; }'.
```