fix(sequencer/anomaly_detection): Fix for inability to build data structure required by anomaly detection.
log from LRT run:
thread 'main' panicked at libs/anomaly_detection/src/extended_isolation_forest.rs:15:53:
called `Result::unwrap()` on an `Err` value: InsufficientTrainingData